### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by rosenbjerg** [molnarmark/preact-flatpickr#1]
I am experiencing this issue:
Module not found: Error: Can't resolve './node_modules/flatpickr/dist/themes' in 'C:\Users\ ...\MyProject\node_modules\preact-flatpickr'
from this usage:
```
<Flatpickr
    theme="dark"
    onChange={() => console.log('You just changed the date.')}>
</Flatpickr>
```

I solved it by changing this:
```require(`./node_modules/flatpickr/dist/themes/${theme}.css`);```
to
```import (`flatpickr/dist/themes/${theme}.css`);```

I have created a pull request for this change.
Please verify that this also works for you :)

**Comment by molnarmark** [comment]
Thank you, merged. :tada:
